package com.example.myapplication.domain.model

import java.util.Date

data class HourlyWeather(
    val weatherType: WeatherType,
    val time: Int,
    val wind: Int,
    val temperature: Int
){
    companion object{
        fun getDefault():List<HourlyWeather>{
            return listOf(
                HourlyWeather(
                    WeatherType.SUNNY,
                    6,
                    21,
                    16
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    7,
                    21,
                    19
                ),
                HourlyWeather(
                    WeatherType.SUNNY,
                    8,
                    20,
                    21
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    9,
                    20,
                    24
                ),
                HourlyWeather(
                    WeatherType.RAINY,
                    10,
                    21,
                    25
                ),
                HourlyWeather(
                    WeatherType.RAINY,
                    11,
                    21,
                    28
                ),
                HourlyWeather(
                    WeatherType.SUNNY,
                    12,
                    19,
                    30
                ),
                HourlyWeather(
                    WeatherType.SUNNY,
                    13,
                    16,
                    31
                ),
                HourlyWeather(
                    WeatherType.SUNNY,
                    14,
                    16,
                    30
                ),
                HourlyWeather(
                    WeatherType.STORMY,
                    15,
                    16,
                    30
                ),
                HourlyWeather(
                    WeatherType.STORMY,
                    16,
                    17,
                    32
                ),
                HourlyWeather(
                    WeatherType.STORMY,
                    17,
                    19,
                    29
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    18,
                    19,
                    27
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    19,
                    20,
                    24
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    20,
                    21,
                    23
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    21,
                    21,
                    20
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    22,
                    22,
                    19
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    23,
                    19,
                    20
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    0,
                    19,
                    18
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    1,
                    21,
                    16
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    2,
                    20,
                    16
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    3,
                    24,
                    14
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    4,
                    28,
                    13
                ),
                HourlyWeather(
                    WeatherType.CLOUDY,
                    5,
                    23,
                    14
                )
            )
        }
    }
}